### ISSUE TITLE
Dear author, how can we run these python files?

### ISSUE THREAD

**Issue by yh-arcsinx** [tsinghua-fib-lab/Activity-Trajectory-Generation#1]

**Comment by yh-arcsinx** [comment]
Dear yuanyuan. I am wondering if you could kindly send me the dataset of your simulation and the necessary information in your article to help me. Thank you very much for your consideration. I am very pleased to hear from you.

**Comment by YuanYuan98** [comment]
Thanks for your attention on our work. I'm sorry that the dataset of mobile network operator is not publicly available due to the strict non-disclosure agreement and privacy issues. The Foursquare dataset can be found in [foursquare-dataset](https://sites.google.com/site/yangdingqi/home/foursquare-dataset).
